/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author phamq
 */
public class formProductDetail extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public formProductDetail() {
        initComponents();
        formLogin.FrameDragListener frameDragListener = new formLogin.FrameDragListener(this);
        this.addMouseListener(frameDragListener);
        this.addMouseMotionListener(frameDragListener);
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);

        Image url = new javax.swing.ImageIcon(getClass().getResource("/Resources/lamborghini_200px.png")).getImage();
        this.setIconImage(url);

        System.out.println("Form opened!");
        name_label.setText(Objects.Cars.Instance.getTenLX());
        amountLeft_label.setText(Objects.Cars.Instance.getSoLuong());
        des_label.setText(Objects.Cars.Instance.getSoCho() + " chỗ ngồi.");
        price_label.setText(Objects.Cars.Instance.getGia());

        System.out.println("Set value successfully!");
        try {
            BufferedImage img = Objects.Cars.Instance.getImageNgoai();
            System.out.println(Objects.Cars.Instance.getImageNgoai());
            System.out.println("Setting the image!");
            img_label.setIcon(new javax.swing.ImageIcon(img));
            scaleImage(img_label);
            System.out.println("Set image successfully!");
        } catch (Exception e) {
            System.out.println("Set image failed!" + e);
        }
    }

    public static void scaleImage(JLabel x) {
        ImageIcon icon = (ImageIcon) x.getIcon();
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(x.getWidth(), x.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon = new ImageIcon(imgScale);
        x.setIcon(scaleIcon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        name_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        des_label = new javax.swing.JLabel();
        price_label = new javax.swing.JLabel();
        amountLeft_label = new javax.swing.JLabel();
        numberProd = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        img_label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 245, 242));

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));
        kGradientPanel1.setkEndColor(new java.awt.Color(102, 102, 102));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 51));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_label.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        name_label.setForeground(new java.awt.Color(255, 204, 0));
        name_label.setText("Tên");
        kGradientPanel1.add(name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 25, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mô Tả");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 136, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Số lượng còn lại:");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 315, -1, 39));

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ok_45px.png"))); // NOI18N
        jButton1.setText("THÊM VÀO GIỎ HÀNG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 220, -1));

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cancel_45px.png"))); // NOI18N
        jButton2.setText("HUỶ");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        kGradientPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/multiply_30px.png"))); // NOI18N
        jLabel15.setText("jLabel4");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        kGradientPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 27, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Giá");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 223, 37, -1));

        des_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        des_label.setForeground(new java.awt.Color(255, 255, 255));
        des_label.setText("jLabel6");
        kGradientPanel1.add(des_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 87, 230, 114));

        price_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        price_label.setForeground(new java.awt.Color(255, 255, 255));
        price_label.setText("jLabel7");
        kGradientPanel1.add(price_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 223, 109, -1));

        amountLeft_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amountLeft_label.setForeground(new java.awt.Color(255, 255, 255));
        amountLeft_label.setText("jLabel8");
        kGradientPanel1.add(amountLeft_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 326, 93, -1));

        numberProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numberProd.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        kGradientPanel1.add(numberProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 278, 80, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(img_label, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img_label, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        );

        kGradientPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 86, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Số lượng:");
        kGradientPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 270, -1, 39));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Objects.Cars c = Objects.Cars.Instance;
            System.out.println(Objects.listCarRental.cars.size());
            if (Objects.listCarRental.cars.size() < 1) {

                System.out.println(Objects.listCarRental.cars.size());

                int amountLeft = processes.getData.getCountMaXe(c.getMaLX());
                if (amountLeft >= (Integer) numberProd.getValue()) {
                    Objects.listCarRental.soluong.add((Integer) numberProd.getValue());
                    Objects.listCarRental.cars.add(c);
                    System.out.println("Data added!");
                    System.out.println("Add soluong successfully!");
                    JOptionPane.showMessageDialog(this, "Thêm thành công!");
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Số lượng bạn chọn quá với số lượng có sẵn, vui lòng chọn lại!");

                }
            } else {
                int index = -1;
                int i = 0;
                for (Objects.Cars cs : Objects.listCarRental.cars) {
                    if (c.getMaLX().equals(cs.getMaLX())) {
                        index = i;
                    }
                    i++;
                }
                if (index != -1) {
                    int amountLeft = processes.getData.getCountMaXe(c.getMaLX());
                    int amountChoosen = Objects.listCarRental.soluong.get(index);
                    int amountChoosing = (Integer) numberProd.getValue();
                    if (amountLeft >= (amountChoosing + amountChoosen)) {
                        Objects.listCarRental.soluong.set(index, amountChoosing + amountChoosen);
                        System.out.println("Add soluong successfully!");
                        JOptionPane.showMessageDialog(this, "Thêm thành công!");
                        this.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(this, "Số lượng bạn chọn quá với số lượng có sẵn, vui lòng chọn lại!");

                    }
                } else {
                    System.out.println(Objects.listCarRental.cars.size());

                    int amountLeft = processes.getData.getCountMaXe(c.getMaLX());
                    if (amountLeft >= (Integer) numberProd.getValue()) {
                        Objects.listCarRental.soluong.add((Integer) numberProd.getValue());
                        Objects.listCarRental.cars.add(c);
                        System.out.println("Data added!");
                        System.out.println("Add soluong successfully!");
                        JOptionPane.showMessageDialog(this, "Thêm thành công!");
                        this.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(this, "Số lượng bạn chọn quá với số lượng có sẵn, vui lòng chọn lại!");

                    }
                }
            }

        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(this, "Thêm thất bại!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2MousePressed

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel15MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formProductDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formProductDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formProductDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formProductDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the formProductDetail */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formProductDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLeft_label;
    private javax.swing.JLabel des_label;
    private javax.swing.JLabel img_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel name_label;
    private javax.swing.JSpinner numberProd;
    private javax.swing.JLabel price_label;
    // End of variables declaration//GEN-END:variables
}
