/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import temp.EditImage;
import static view.formSignUp.isNumeric;
import static view.formSignUp.patternMatches;

/**
 *
 * @author phamq
 */
public class formAddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public static void moveForm(JFrame x) {
        formLogin.FrameDragListener frameDragListener = new formLogin.FrameDragListener(x);
        x.addMouseListener(frameDragListener);
        x.addMouseMotionListener(frameDragListener);
        x.pack();
        x.setLocationRelativeTo(null);
        x.setVisible(true);
    }

    public formAddEmployee() {
        initComponents();
        moveForm(this);

        //set icon logo
        Image url = new javax.swing.ImageIcon(getClass().getResource("/Resources/lamborghini_200px.png")).getImage();
        this.setIconImage(url);
        mail_check.setVisible(false);
        phone_check.setVisible(false);
        username_check.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name_Field = new javax.swing.JTextField();
        dob_Field = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        address_Field = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        email_Field = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        phoneNumber_Field = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        rePassword_Field = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        password_Field = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        username_Field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mail_check = new javax.swing.JLabel();
        phone_check = new javax.swing.JLabel();
        username_check = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM NHÂN VIÊN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Họ và tên");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 80, 70, -1));

        name_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_FieldActionPerformed(evt);
            }
        });
        jPanel1.add(name_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, 228, -1));

        dob_Field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dob_Field.setDateFormatString("dd/mm/yyyy");
        jPanel1.add(dob_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 97, 146, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Ngày sinh");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 80, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Địa Chỉ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 131, -1, 25));

        address_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_FieldActionPerformed(evt);
            }
        });
        jPanel1.add(address_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, 570, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Email");
        jLabel12.setToolTipText("");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, 100, -1));

        email_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_FieldActionPerformed(evt);
            }
        });
        email_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                email_FieldKeyPressed(evt);
            }
        });
        jPanel1.add(email_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 198, 270, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Số điện thoại");
        jLabel14.setToolTipText("");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 181, 100, -1));

        phoneNumber_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumber_FieldActionPerformed(evt);
            }
        });
        phoneNumber_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneNumber_FieldKeyPressed(evt);
            }
        });
        jPanel1.add(phoneNumber_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 198, 280, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 379, 246, 110));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 509, 246, 110));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/multiply_30px.png"))); // NOI18N
        jLabel15.setText("jLabel4");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 6, 27, 20));

        kGradientPanel2.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel2.setkGradientFocus(1000);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 0, 51));
        kGradientPanel2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                kGradientPanel2ComponentAdded(evt);
            }
        });
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(102, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cancel_45px.png"))); // NOI18N
        jButton4.setText("Huỷ");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 670, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 102, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ok_45px.png"))); // NOI18N
        jButton3.setText("Thêm nhân viên");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 670, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("CMND mặt trước");
        kGradientPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 25));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Chọn ảnh");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 104, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Chọn ảnh");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 104, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("CMND mặt sau");
        kGradientPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 104, 29));
        kGradientPanel2.add(rePassword_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 162, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Nhập lại mật khẩu");
        kGradientPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 120, -1));
        kGradientPanel2.add(password_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 162, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Mật khẩu");
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 80, -1));

        username_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_FieldActionPerformed(evt);
            }
        });
        username_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                username_FieldKeyPressed(evt);
            }
        });
        kGradientPanel2.add(username_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 162, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Tên đăng nhập");
        kGradientPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 20));

        mail_check.setForeground(new java.awt.Color(255, 255, 255));
        mail_check.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mail_check.setText("jLabel3");
        kGradientPanel2.add(mail_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 224, 270, 20));

        phone_check.setForeground(new java.awt.Color(255, 255, 255));
        phone_check.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phone_check.setText("jLabel16");
        kGradientPanel2.add(phone_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 224, 280, 20));

        username_check.setForeground(new java.awt.Color(255, 255, 255));
        username_check.setText("username_check");
        kGradientPanel2.add(username_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 190, 20));

        jPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_FieldActionPerformed

    private void address_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_FieldActionPerformed

    private void username_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_FieldActionPerformed

    private void email_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_FieldActionPerformed

    private void phoneNumber_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumber_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumber_FieldActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("hinh hanh", "jpg", "png", "gif");
        fileChooser.setFileFilter(imageFilter);
        fileChooser.setMultiSelectionEnabled(false);

        int respone = fileChooser.showDialog(this, "Chon file");
        if (respone == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            jLabel10.setIcon(new ImageIcon(file.getAbsolutePath()));
            EditImage.scaleImage(jLabel10);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
//        JFileChooser fileChooser = new JFileChooser();
//        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("hinh hanh", "jpg", "png", "gif");
//        fileChooser.setFileFilter(imageFilter);
//        fileChooser.setMultiSelectionEnabled(false);
//
//        int respone = fileChooser.showDialog(this, "Chon file");
//        if (respone == JFileChooser.APPROVE_OPTION) {
//            File file = fileChooser.getSelectedFile();
//            jLabel11.setIcon(new ImageIcon(file.getAbsolutePath()));
//            EditImage.scaleImage(jLabel1);
//        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4MousePressed

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        this.dispose();
    }//GEN-LAST:event_jLabel15MousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private File f1, f2;

    private String regexPattern = "^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$";

    public static boolean patternMatches(String emailAddress, String regexPattern) {
        return Pattern.compile(regexPattern)
                .matcher(emailAddress)
                .matches();
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String Dob = "";
            String Name = "";
            String Address = "";
            String Email = "";
            String Password = "";
            String rePassword = "";
            String PhoneNum = "";
            String Username = "";
            String CMND_T = "";
            String CMND_S = "";
            CMND_T = f1.getAbsolutePath();
            CMND_S = f2.getAbsolutePath();

            DateFormat dateFormat = new SimpleDateFormat("dd/mm/yyyy");
            try {
                Name = name_Field.getText();
                Address = address_Field.getText();

                if (patternMatches(email_Field.getText(), regexPattern)) {
                    Email = email_Field.getText();
                }

                Password = new String(password_Field.getPassword());
                rePassword = new String(rePassword_Field.getPassword());
                if (isNumeric(phoneNumber_Field.getText())) {
                    PhoneNum = phoneNumber_Field.getText();
                }
                Username = username_Field.getText();
                Dob = dateFormat.format(dob_Field.getDate());
                CMND_T = f1.getAbsolutePath();
                CMND_S = f2.getAbsolutePath();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Đăng ký thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
            System.out.println(Name);
            System.out.println(Dob);
            System.out.println(Email);
            System.out.println(Password);
            System.out.println(rePassword);
            System.out.println(PhoneNum);
            System.out.println(Username);

            if (Password.equals(rePassword) && PhoneNum != "" && Email != "") {
                processes.insertData.SignUpEmployee(Name, Username, Email, Password, Address, CMND_T, CMND_S, PhoneNum, Dob, "NHANVIEN");

                this.dispose();
            } else {
                if (!PhoneNum.equals("")) {
                    JOptionPane.showMessageDialog(null, "Mật khẩu nhập lại không giống nhau, vui lòng nhập lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Số điện thoại nhập không hợp lệ, vui lòng nhập lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
                if (Email.equals("")) {
                    JOptionPane.showMessageDialog(null, "Email không hợp lệ, vui lòng nhập lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Đăng ký thất bại, vui lòng nhập đúng và đầy đủ thông tin!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Choose Image", "jpg", "png", "gif");
        fileChooser.setFileFilter(imageFilter);
        fileChooser.setMultiSelectionEnabled(false);

        int respone = fileChooser.showDialog(this, "Choose file");
        if (respone == JFileChooser.APPROVE_OPTION) {
            f1 = fileChooser.getSelectedFile();
            jLabel10.setIcon(new ImageIcon(f1.getAbsolutePath()));
            EditImage.scaleImage(jLabel10);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static boolean isNumeric(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("hinh hanh", "jpg", "png", "gif");
        fileChooser.setFileFilter(imageFilter);
        fileChooser.setMultiSelectionEnabled(false);

        int respone = fileChooser.showDialog(this, "Chon file");
        if (respone == JFileChooser.APPROVE_OPTION) {
            f2 = fileChooser.getSelectedFile();
            jLabel11.setIcon(new ImageIcon(f2.getAbsolutePath()));
            EditImage.scaleImage(jLabel11);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void kGradientPanel2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_kGradientPanel2ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_kGradientPanel2ComponentAdded

    private void email_FieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_email_FieldKeyPressed
        if (!patternMatches(email_Field.getText(), regexPattern)) {
            mail_check.setText("Vui lòng nhập đúng định dạng email!");
            mail_check.setVisible(true);
        } else {
            mail_check.setVisible(false);
        }

    }//GEN-LAST:event_email_FieldKeyPressed

    private void phoneNumber_FieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumber_FieldKeyPressed
        if (!isNumeric(phoneNumber_Field.getText())) {
            phone_check.setText("Định dạng số điện thoại sai!");
            phone_check.setVisible(true);
        } else {
            phone_check.setVisible(false);
        }
    }//GEN-LAST:event_phoneNumber_FieldKeyPressed

    private String regularExpression = "^[a-zA-Z][a-zA-Z0-9_]{6,19}$";

    private void username_FieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_FieldKeyPressed
        System.out.println("Checking validate...");
        if (!isUsername(username_Field.getText())) {
            username_check.setVisible(true);
            username_check.setText("Tên đăng nhập không hợp lệ!");

        } else {
            username_check.setVisible(false);

        }
    }//GEN-LAST:event_username_FieldKeyPressed

    private static String username_pattern = "^[a-zA-Z0-9]([._-](?![._-])|[a-zA-Z0-9]){3,18}[a-zA-Z0-9]$";

    public static Boolean isUsername(String username) {
        int flag = 0;
        try {
            Pattern pattern = Pattern.compile(username_pattern);
            Matcher matcher = pattern.matcher(username);
            if (matcher.matches()) {
                flag = 1;
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
        return flag == 1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formAddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_Field;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dob_Field;
    private javax.swing.JTextField email_Field;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel mail_check;
    private javax.swing.JTextField name_Field;
    private javax.swing.JPasswordField password_Field;
    private javax.swing.JTextField phoneNumber_Field;
    private javax.swing.JLabel phone_check;
    private javax.swing.JPasswordField rePassword_Field;
    private javax.swing.JTextField username_Field;
    private javax.swing.JLabel username_check;
    // End of variables declaration//GEN-END:variables
}
