/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phamq
 */
public class formRentalCart extends javax.swing.JInternalFrame {

    /**
     * Creates new form temp2
     */
    public formRentalCart() {
        initComponents();
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCars_table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        start_Date = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        end_Date = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(17, 43, 60));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1109, 680));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1109, 680));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THÔNG TIN THUÊ XE");

        listCars_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        listCars_table.setRowHeight(160);
        listCars_table.setRowMargin(5);
        listCars_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCars_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listCars_table);

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ok_45px.png"))); // NOI18N
        jButton1.setText("Thuê xe");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cancel_45px.png"))); // NOI18N
        jButton2.setText("Xoá");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ngày nhận xe");

        start_Date.setDateFormatString("dd/MM/yyyy");
        start_Date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ngày trả xe");

        end_Date.setDateFormatString("dd/MM/yyyy");
        end_Date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(start_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(end_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(start_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(end_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listCars_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCars_tableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_listCars_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int checkBlacklist = processes.getData.getBlacklistById(Objects.User.Instance.getMaND());
        if (checkBlacklist < 3) {
            String MaND = Objects.User.Instance.getMaND();
            String listMaXe = "";
            String listSoLuong = "";
            int count = Objects.listCarRental.cars.size();
            if (count > 0) {
                listMaXe = Objects.listCarRental.cars.get(0).getMaLX();
                listSoLuong = Objects.listCarRental.soluong.get(0).toString();
                for (int i = 1; i < count; i++) {
                    listMaXe += ",";
                    listMaXe += Objects.listCarRental.cars.get(i).getMaLX();
                    listSoLuong += ",";
                    listSoLuong += Objects.listCarRental.soluong.get(i).toString();
                }
            }

            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String startDate = "";
            String endDate = "";
//                
            try {
                startDate = dateFormat.format(start_Date.getDate());
//        
                endDate = dateFormat.format(end_Date.getDate());
                listMaXe = listMaXe.replace(" ", "");
                System.out.println(startDate + " " + endDate);
                System.out.println(listMaXe);
                System.out.println(listSoLuong);

                try {
                    processes.insertData.RentCars(MaND, startDate, endDate, listMaXe, listSoLuong);
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Cập nhật thất bại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    System.out.println("Rent car failed!" + e);
                }
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Cập nhật thất bại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }

            Objects.listCarRental.cars.clear();
            Objects.listCarRental.soluong.clear();
            listCars_table.removeAll();

            loadData();
        }else
        {
            JOptionPane.showMessageDialog(null, "Bạn không thể thuê xe vì đã hủy hợp đồng quá 3 lần", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void loadData() {
        try {
            DefaultTableModel dtm = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }

            };
            dtm.addColumn("Tên Xe");
            dtm.addColumn("Số lượng");
            dtm.addColumn("Giá");
            dtm.addColumn("Hình ảnh");

            int n = Objects.listCarRental.cars.size();
            System.out.println("So luong san pham trong gio " + n);

            if (n > 0) {
                for (int i = 0; i < n; i++) {
                    Objects.Cars c = Objects.listCarRental.cars.get(i);
                    String soLuong = Objects.listCarRental.soluong.get(i).toString();
                    dtm.addRow(new Object[]{
                        c.getTenLX(), soLuong, c.getGia(), c.getImageNgoai()
                    });
                }
            }

            listCars_table.setModel(dtm);
            listCars_table.getColumnModel().getColumn(3).setCellRenderer(new ImageRender());
            
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            listCars_table.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
            listCars_table.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
            listCars_table.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
      
        } catch (Exception e) {
            System.out.println("An error orcur!" + e);
        }
    }

    private class ImageRender extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            try {
                //String photoName = value.toString();
                BufferedImage img = (BufferedImage) value;
                ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(128, 128, Image.SCALE_DEFAULT));
                return new JLabel(imgIcon);
            } catch (Exception ex) {
                Logger.getLogger(formOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
            return null;

        }

    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int index = listCars_table.getSelectedRow();

        Objects.listCarRental.cars.remove(index);
        Objects.listCarRental.soluong.remove(index);

        loadData();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser end_Date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listCars_table;
    private com.toedter.calendar.JDateChooser start_Date;
    // End of variables declaration//GEN-END:variables
}
